[package]
name = "leetcode"
version = "0.1.0"
authors = ["Raphanus Lo <coldturnip@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leetcode_prelude = "0.2"
